export const FILTERS_VALUE_REQUEST = "FILTERS_VALUE_REQUEST";
export const FILTERS_VALUE_SUCCESS = "FILTERS_VALUE_SUCCESS";

export const PLAYLISTS_REQUEST = "PLAYLISTS_REQUEST";
export const PLAYLISTS_SUCCESS = "PLAYLISTS_SUCCESS";
export const PLAYLISTS_FAILED = "PLAYLISTS_FAILED";

export const SEARCH_NAME_PLAYLIST = "SEARCH_NAME_PLAYLIST";

export const FILTERS_API = "FILTERS_API";